---

- name: perform installation
  include_tasks: install/{{ ansible_os_family }}.yml

- name: on postgres host -- create database
  throttle: 1
  delegate_to: "{{ postgres_client_host }}"
  become_user: postgres
  become: true
  postgresql_db:
    encoding: "UTF-8"
    name: "{{ postgres_client_db }}"
    template: "{{ postgres_client_template }}"
  when: postgres_client_create_user_and_db

- name: on postgres host -- create user and grant permissions on database
  throttle: 1
  delegate_to: "{{ postgres_client_host }}"
  become_user: postgres
  become: true
  postgresql_user:
    db: "{{ postgres_client_db }}"
    name: "{{ postgres_client_user }}"
    encrypted: true
    password: "md5{{ [postgres_client_password, postgres_client_user]|join('')|hash('md5') }}"
    priv: ALL
    role_attr_flags: SUPERUSER
  when: postgres_client_create_user_and_db

- name: install postgres extensions
  throttle: 1
  delegate_to: "{{ postgres_client_host }}"
  become_user: postgres
  become: true
  postgresql_ext:
    name: "{{ item }}"
    db: "{{ postgres_client_db }}"
    state: present
  loop: "{{ postgres_client_extensions|default([]) }}"
  when: postgres_client_create_user_and_db
